// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oponeo.Infrastructure;

#nullable disable

namespace Oponeo.Migrations.Migrations
{
    [DbContext(typeof(OponeoContext))]
    [Migration("20220311130855_Offers-with-parameters-tph")]
    partial class Offerswithparameterstph
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Oponeo.Domain.ExampleObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DecimalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExampleStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntValue")
                        .HasPrecision(19, 2)
                        .HasColumnType("int");

                    b.Property<string>("StringValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ExampleObjects");
                });

            modelBuilder.Entity("Oponeo.Domain.Offer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Option2")
                        .HasColumnType("int");

                    b.Property<string>("OptionOfferStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Oponeo.Domain.Parameter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("Parameters");

                    b.HasDiscriminator<string>("Type").HasValue("Parameter");
                });

            modelBuilder.Entity("Oponeo.Domain.SubExampleObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("ExampleObjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExampleObjectId");

                    b.ToTable("SubExampleObject");
                });

            modelBuilder.Entity("Oponeo.Domain.IntParameter", b =>
                {
                    b.HasBaseType("Oponeo.Domain.Parameter");

                    b.Property<int?>("IntValue")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Int");
                });

            modelBuilder.Entity("Oponeo.Domain.StringParameter", b =>
                {
                    b.HasBaseType("Oponeo.Domain.Parameter");

                    b.Property<string>("StringValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("String");
                });

            modelBuilder.Entity("Oponeo.Domain.Parameter", b =>
                {
                    b.HasOne("Oponeo.Domain.Offer", null)
                        .WithMany("Parameters")
                        .HasForeignKey("OfferId");
                });

            modelBuilder.Entity("Oponeo.Domain.SubExampleObject", b =>
                {
                    b.HasOne("Oponeo.Domain.ExampleObject", "ExampleObject")
                        .WithMany("SubExampleObjects")
                        .HasForeignKey("ExampleObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExampleObject");
                });

            modelBuilder.Entity("Oponeo.Domain.ExampleObject", b =>
                {
                    b.Navigation("SubExampleObjects");
                });

            modelBuilder.Entity("Oponeo.Domain.Offer", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
